# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  sorcery_github_callback_url: "https://sinder.herokuapp.com/oauth/callback?provider=github"
  sorcery_github_key: <%= SORCERY_GITHUB_CONFIG["app_id"] %>
  sorcery_github_secret: <%= SORCERY_GITHUB_CONFIG["secret"] %>

test:
  sorcery_github_key: <%= SORCERY_GITHUB_CONFIG['app_id'] %>
  sorcery_github_secret: <%= SORCERY_GITHUB_CONFIG["secret"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  sorcery_github_callback_url: <%= ENV["SORCERY_GITHUB_CALLBACK_URL"] %>
  sorcery_github_key: <%= SORCERY_GITHUB_CONFIG['app_id'] %>
  sorcery_github_secret: <%= SORCERY_GITHUB_CONFIG["secret"] %>
